[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = ["g", "d"]
run  = "cd ~/Downloads"
desc = "CD to ~/Downloads"

[[mgr.prepend_keymap]]
on   = ["g", "c"]
run  = "cd ~/.local/share/chezmoi"
desc = "CD to chezmoi"

[[mgr.prepend_keymap]]
on   = ["g", "D"]
run  = "cd ~/Documents"
desc = "CD to ~/Documents"
