return {}
-- return {
--   "nvim-neorg/neorg",
--   version = "^9",
--   dependencies = { "nvim-treesitter/nvim-treesitter" },
--   opts = function(_, opts)
--     local astrocore = require("astrocore")
--     return astrocore.extend_tbl(opts, {
--       load = {
--         ["core.defaults"] = {},                       -- Loads default behaviour
--         ["core.concealer"] = {},                      -- Adds pretty icons to your documents
--         ["core.keybinds"] = { default_keybinds = false }, -- Adds default keybindings
--         ["core.journal"] = {},                        -- Enables support for the journal module
--         ["core.dirman"] = {                           -- Manages Neorg workspaces
--           config = {
--             workspaces = {
--               notes = "~/Projects/notes",
--             },
--             default_workspace = "notes",
--           },
--         },
--       },
--     })
--   end,
--   specs = {
--     {
--       "nvim-treesitter/nvim-treesitter",
--       opts = function(_, opts)
--         if opts.ensure_installed ~= "all" then
--           opts.ensure_installed = require("astrocore").list_insert_unique(opts.ensure_installed, { "norg" })
--         end
--       end,
--     },
--   },
-- }
