#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "GeoClue Wi-Fi positioning setup"

policy_source="$HOME/.config/weather/geoclue-wpa-supplicant.conf"
policy_target="/etc/dbus-1/system.d/geoclue-wpa-supplicant.conf"
weather_script="$HOME/.config/weather/weather.py"
override="$HOME/.config/weather/location.json"
result_file="$HOME/.cache/weather/geoclue-wifi-policy-result.txt"
provider_source="$HOME/.config/weather/geoclue-wifi-provider.conf"
provider_target="/etc/geoclue/conf.d/90-weather-wifi-provider.conf"
install -Dm600 /dev/null "$result_file"

probe_location() {
  local seconds="$1" output
  output=$(/usr/lib/geoclue-2.0/demos/where-am-i -t "$seconds" -a 6)
  description=$(printf '%s\n' "$output" | sed -n 's/^Description:[[:space:]]*//p' | tail -n1)
  accuracy=$(printf '%s\n' "$output" | sed -n 's/^Accuracy:[[:space:]]*\([0-9][0-9]*\) meters.*/\1/p' | tail -n1)
}

precise_wifi_fix() {
  [[ "$description" == WiFi* && "$accuracy" =~ ^[0-9]+$ && "$accuracy" -le 1000 ]]
}

enable_automatic_weather() {
  if [[ -f "$override" ]] && confirm "Disable the manual location override and use automatic positioning?"; then
    override_backup="${override}.manual-backup"
    mv "$override" "$override_backup"
    if python3 "$weather_script" --refresh >/dev/null; then
      pkill -RTMIN+8 waybar || true
      say "✓ Automatic weather refreshed; backup kept at $override_backup"
    else
      mv "$override_backup" "$override"
      warn "Automatic refresh failed; restored the manual override."
      return 1
    fi
  elif [[ ! -f "$override" ]]; then
    python3 "$weather_script" --refresh >/dev/null
    pkill -RTMIN+8 waybar || true
    say "✓ Automatic weather refreshed."
  else
    note "Manual override retained."
  fi
}

stage "Validate and install the D-Bus policy"
say "This policy grants the geoclue service account only bulk property reads,"
say "Wi-Fi scan requests and scan-result signals from wpa_supplicant."
step "Review the policy at: $policy_source"
xmllint --noout "$policy_source"
say "✓ XML validation passed."
if cmp --silent "$policy_source" "$policy_target" 2>/dev/null; then
  say "✓ The installed policy already matches."
elif confirm "Install the policy under /etc? Administrator authentication is required."; then
  sudo install -Dm644 "$policy_source" "$policy_target"
  sudo cmp --silent "$policy_source" "$policy_target"
  say "✓ Installed and verified: $policy_target"
else
  warn "Policy installation declined."
  exit 1
fi

stage "Activate the policy"
say "D-Bus supports policy reloads on this system; GeoClue must reconnect afterward."
if confirm "Reload system D-Bus policy and restart GeoClue now?"; then
  sudo systemctl reload dbus.service
  sudo systemctl restart geoclue.service
  say "✓ D-Bus reloaded and GeoClue restarted."
else
  warn "Activation declined; the installed policy is not active yet."
  exit 1
fi

stage "Verify restricted wpa_supplicant access"
say "This checks only interface and BSS object counts; it does not print SSIDs or addresses."
if ! interface_line=$(sudo -u geoclue busctl --system call \
  fi.w1.wpa_supplicant1 /fi/w1/wpa_supplicant1 \
  org.freedesktop.DBus.Properties GetAll s fi.w1.wpa_supplicant1); then
  printf 'scan_access=denied\n' > "$result_file"
  warn "The geoclue account cannot query wpa_supplicant."
  pause "Press Enter to close."
  exit 1
fi
interface_path=$(printf '%s\n' "$interface_line" | sed -n \
  's/.*"Interfaces" ao [0-9][0-9]* "\([^"]*\)".*/\1/p')
if [[ -z "$interface_path" ]]; then
  printf 'scan_access=no_interface\n' > "$result_file"
  warn "The geoclue account cannot see a Wi-Fi interface."
  pause "Press Enter to close."
  exit 1
fi
if ! sudo -u geoclue busctl --system call fi.w1.wpa_supplicant1 "$interface_path" \
  fi.w1.wpa_supplicant1.Interface Scan 'a{sv}' 1 Type s passive >/dev/null; then
  printf 'scan_access=scan_denied\n' > "$result_file"
  warn "The geoclue account can read the interface but cannot request a scan."
  pause "Press Enter to close."
  exit 1
fi
sleep 4
if ! bss_line=$(sudo -u geoclue busctl --system call \
  fi.w1.wpa_supplicant1 "$interface_path" \
  org.freedesktop.DBus.Properties GetAll s fi.w1.wpa_supplicant1.Interface); then
  printf 'scan_access=bss_read_denied\n' > "$result_file"
  warn "The geoclue account cannot read scan-result objects."
  pause "Press Enter to close."
  exit 1
fi
bss_count=$(printf '%s\n' "$bss_line" | sed -n 's/.*"BSSs" ao \([0-9][0-9]*\).*/\1/p')
printf 'scan_access=allowed\nbss_count=%s\n' "${bss_count:-unknown}" > "$result_file"
say "Visible Wi-Fi BSS objects: ${bss_count:-unknown}"
if [[ ! "$bss_count" =~ ^[0-9]+$ || "$bss_count" -eq 0 ]]; then
  warn "No access-point scan results are visible to GeoClue."
  pause "Press Enter to close."
  exit 1
fi
say "✓ GeoClue can request scans and read the resulting BSS objects."

stage "Verify Wi-Fi positioning and refresh Waybar"
say "The probe runs for 25 seconds and prints only source description and accuracy."
probe_location 25
printf 'default_source=%s\ndefault_accuracy=%s\n' "${description:-unknown}" "${accuracy:-unknown}" >> "$result_file"
say "Source: ${description:-unknown}"
say "Accuracy: ${accuracy:-unknown} metres"

if precise_wifi_fix; then
  say "✓ GeoClue is using a precise Wi-Fi fix."
  enable_automatic_weather
  finish
  exit 0
fi
warn "BeaconDB received Wi-Fi data but returned an IP fallback for these access points."

stage "Try the distribution-supported fallback provider"
say "Positon receives BSS identifiers and signal levels, as any Wi-Fi positioning service must."
say "Its notice says request data is not stored except in a global cache; IP logs are anonymized"
say "and deleted after 14 days. Location submission remains disabled."
if ! confirm "Use GeoClue's distribution-provided Positon endpoint instead of BeaconDB?"; then
  SKIPPED+=("automatic positioning: BeaconDB has no local coverage and Positon was declined")
  warn "The manual override was retained."
  finish
  exit 0
fi
provider_url=$(sed -n 's|^#url=\(https://api\.positon\.xyz/v1/geolocate?key=[A-Za-z0-9-]*\)$|\1|p' \
  /etc/geoclue/geoclue.conf | head -n1)
if [[ -z "$provider_url" ]]; then
  warn "This GeoClue package does not provide a Positon endpoint."
  SKIPPED+=("automatic positioning: no distribution-supported fallback provider")
  finish
  exit 1
fi
provider_temp=$(mktemp)
sed "s|@POSITON_URL@|$provider_url|" "$provider_source" > "$provider_temp"
sudo install -Dm644 "$provider_temp" "$provider_target"
rm -f "$provider_temp"
sudo systemctl restart geoclue.service
probe_location 25
printf 'fallback_source=%s\nfallback_accuracy=%s\n' "${description:-unknown}" "${accuracy:-unknown}" >> "$result_file"
say "Source: ${description:-unknown}"
say "Accuracy: ${accuracy:-unknown} metres"
if precise_wifi_fix; then
  say "✓ GeoClue is using a precise Wi-Fi fix through Positon."
  enable_automatic_weather
else
  sudo rm -f "$provider_target"
  sudo systemctl restart geoclue.service
  SKIPPED+=("automatic positioning: neither provider returned a ≤1 km Wi-Fi fix")
  warn "Positon also lacked a precise result; its override was removed and the manual city retained."
fi

finish
